// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BoardIndex: typeof import('./components/BoardIndex.md')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DragBox: typeof import('./components/drag/Box.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolsCalculator: typeof import('./components/tools/Calculator.vue')['default']
    ToolsCountNumber: typeof import('./components/tools/CountNumber.vue')['default']
    ToolsDice6: typeof import('./components/tools/Dice6.vue')['default']
    ToolsFinancialStatement: typeof import('./components/tools/FinancialStatement/index.vue')['default']
    ToolsReservedDice: typeof import('./components/tools/reserved/Dice.vue')['default']
  }
}

export {}
